### ISSUE TITLE
Strange python non blocking error message while using pyslurm.node() nodes.get()

### ISSUE THREAD

**Issue by laparn** [gingergeeks/pyslurm#28]
When using pyslurm.node, I get the following behaviour  : 

Python 2.7.3 (default, Aug  1 2012, 05:14:39) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyslurm
>>> nodes = pyslurm.node()
>>> nodes_dict = nodes.get()
python: error: Unsupported option 4 for get_nodeinfo.
python: error: Unsupported option 4 for get_nodeinfo.

There are useful information in nodes_dict after that. However, the error message is disturbing. This is a totally non critical error. I use slurm2.5 and a trunk version of pyslurm.

**Comment by gingergeeks** [comment]
I reworked the code a long time ago for this so it should be closed. Please reopen if still a problem
