### ISSUE TITLE
No symbols in python module

### ISSUE THREAD

**Issue by sqlboy** [gingergeeks/pyslurm#35]
After compiling with cython 0.19 and 2.5.7 my module has nothing in it.

>>> dir(pyslurm)
['DLFCN', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__', 'absolute_import', 'old_dlopen_flags', 'os', 'sys', 'version']

any ideas?

**Comment by gingergeeks** [comment]
No info for this, if this still an issue then please reopen.
