### ISSUE TITLE
Doesn't build with slurm-14.03.8 and Cython-0.20

### ISSUE THREAD

**Issue by olahaye74** [gingergeeks/pyslurm#38]
Even when patching setup.py to build with newer python version, the build fails.
building 'pyslurm.pyslurm' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/pyslurm
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include -I. -I/usr/include/python2.7 -c pyslurm/pyslurm.c -o build/temp.linux-x86_64-2.7/pyslurm/pyslurm.o
pyslurm/pyslurm.c: In function ‘__pyx_f_7pyslurm_7pyslurm_6config___get’:
pyslurm/pyslurm.c:8641:5: attention : passing argument 1 of ‘__Pyx_PyInt_From_uint16_t’ makes integer from pointer without a cast [enabled by default]
     __pyx_t_1 = __Pyx_PyInt_From_uint16_t(__pyx_v_self->__pyx___Config_ptr->job_acct_gather_freq); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 407; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
     ^
pyslurm/pyslurm.c:2145:29: note: expected ‘uint16_t’ but argument is of type ‘char *’
 static CYTHON_INLINE PyObject* __Pyx_PyInt_From_uint16_t(uint16_t value);
                             ^
pyslurm/pyslurm.c: In function ‘__pyx_f_7pyslurm_7pyslurm_slurm_requeue’:
pyslurm/pyslurm.c:15177:3: erreur: too few arguments to function ‘slurm_requeue’
   __pyx_v_errCode = slurm_requeue(__pyx_v_JobID);
   ^
In file included from pyslurm/pyslurm.c:345:0:
/usr/include/slurm/slurm.h:3758:12: note: declared here
 extern int slurm_requeue PARAMS((uint32_t job_id, uint32_t state));
            ^
pyslurm/pyslurm.c: In function ‘__pyx_f_7pyslurm_7pyslurm_slurm_terminate_job’:
pyslurm/pyslurm.c:16682:3: attention : implicit declaration of function ‘slurm_terminate_job’ [-Wimplicit-function-declaration]
   __pyx_v_errCode = slurm_terminate_job(__pyx_v_JobID);
   ^
error: command 'gcc' failed with exit status 1

Is this project dead?

**Comment by gingergeeks** [comment]
A dead thread
