### ISSUE TITLE
refuses to build on 0x0e0b04 (14.11.4) but appears to work

### ISSUE THREAD

**Issue by anderbubble** [gingergeeks/pyslurm#42]
I changed setup.py to allow building against 14.11.4, and it built successfully.

    diff --git a/setup.py b/setup.py
    index fb1aa70..1ed7e5b 100644
    --- a/setup.py
    +++ b/setup.py
    @@ -24,7 +24,7 @@ logging.basicConfig(level=20)
     #VERSION = imp.load_source("/tmp", "pyslurm/__init__.py").__version__
     __version__ = "14.11.0-0"
     __min_slurm_hex_version__ = "0x0e0b00"
    -__max_slurm_hex_version__ = "0x0e0b02"
    +__max_slurm_hex_version__ = "0x0e0b04"
 
     def fatal(logstring, code=1):
            logger.error("Fatal: " + logstring)

Running the "Query Node List" [example](http://www.gingergeeks.co.uk/pyslurm/examples.html) worked, too.

Can setup.py be updated to allow building against 14.11.4?

**Comment by gingergeeks** [comment]
Anderbubble,
                     You are quite correct with the suggestion. I checked the Slurm 14.11.4 API when it was released and nothing has changed and the min-max checked in setup.py is designed for exactly this situation. I will add your change later tonight.

Best Regards

**Comment by anderbubble** [comment]
Any chance I could do the full fork/commit/pull request dance to get my own
commit in the tree? It'd be a first for me. :)

~jonathon
