### ISSUE TITLE
Segmentation fault on pyslurm.node()

### ISSUE THREAD

**Issue by ajmazurie** [gingergeeks/pyslurm#52]
Here is an example of session with Pyslurm triggering the error message:

```python
Python 2.7.9 (default, Feb 23 2015, 14:53:24) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyslurm
>>> pyslurm.version()
'14.11.5'
>>> pyslurm.slurm_api_version()
(14, 11, 6)
>>> pyslurm.node()
Segmentation fault
```

Best,
Aurélien

**Comment by gingergeeks** [comment]
Yep, this is has been raised by Jonathon Anderson on the Slurm mailing list and I'm currently working on it. How many nodes in your cluster ? The reason I ask is so I can recreate the issue.

**Comment by ajmazurie** [comment]
I'll have to check but we're above 40 nodes at that point.
Aurélien

**Comment by gingergeeks** [comment]
Sometime ago, I changed the code so I could track and manage the change in data (various classes) from the Slurm API so that looped monitoring programs could be used. Clearly I have a memory issue here but this was showing up on my small test VM.

**Comment by gingergeeks** [comment]
Aurélien,
             I have traced a possible cause to a defined node in the config which does not truly exist. The Slurm API returns a record for it but with no data content. A quick check for a node name of NULL in the record was all that was necessary, does this match your configuration ?

Mark

**Comment by ajmazurie** [comment]
Mark,
I'll have to get back to you on this. Are you asking if one of the node has a name 'NULL'?

Aurélien

**Comment by gingergeeks** [comment]
Aurélien,
              It was a statement that we have traced the problem to a bug in PySlurm and not handling a node record with an empty nodename entry. I think this is where nodes have been entered in the slurm config but do not actually exist in the hosts file or DNS. My question was if it is possible that you have nodes in your config that do not actually exist ?

Mark

**Comment by gingergeeks** [comment]
Aurélien,
              If you pull the latest 14.11.5 the patch as discussed previously has been committed. Please let me know if this now works and close the ticket if you are happy.

Mark

**Comment by ajmazurie** [comment]
Maybe... I do not have a complete understanding of how the cluster is managed, unfortunately.
Aurélien

**Comment by gingergeeks** [comment]
Aurélien,
              This should now be resolved with the latest pyslurm-14.11.5 commits. So please test and close the ticket if it is fixed.

Mark

**Comment by gingergeeks** [comment]
Aurélien,
              Have you had chance to test and confirm it is now resolved ?

Mark

**Comment by gingergeeks** [comment]
Closing this as resolved
