### ISSUE TITLE
ImportError: No module named pyslurm

### ISSUE THREAD

**Issue by MikeDacre** [gingergeeks/pyslurm#53]
This may be me just being stupid, but after successfully building and installing pyslurm, when I run ``import pyslurm`` from an interactive python shell, I get the following error:

    Python 2.7.5 (default, Dec  3 2013, 08:35:16) 
    [GCC 4.4.6 20120305 (Red Hat 4.4.6-4)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pyslurm
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "pyslurm/__init__.py", line 17, in <module>
        from .pyslurm import *
    ImportError: No module named pyslurm
    >>> 

Any ideas what could be going on there?

**Comment by MikeDacre** [comment]
I fixed this myself by removing the leading dot from the ``from .pyslurm import *`` making it ``from pyslurm import *``. That seemed to work, although now when I try to run one of the examples I am getting ``python: symbol lookup error: /usr/lib64/slurm/auth_munge.so: undefined symbol: slurm_debug``. I guess the sysadmin didn't install the debug module for slurm.

**Comment by gingergeeks** [comment]
Mike,
        This is because probably because you were in the pyslurm build directory which itself has a pyslurm directory. I bet if you changed into a directory with no pyslurm directory it will work. Of couse you should put back the "from .pyslurm import *" relative import statement.

Mark

**Comment by MikeDacre** [comment]
Yes, I realized that. I was being dumb. I returned it to its previous value and it works fine now. Thanks for the help.
