### ISSUE TITLE
Python3: More string issues

### ISSUE THREAD

**Issue by MikeDacre** [gingergeeks/pyslurm#55]
In python3, the dictionary returned by job().get() (and all other similar functions) returns plain strings where binary strings are expected, except formatted to include the ``b''`` syntax. I know this is confusing, so here is what I mean:

python2::

    from pyslurm import job
    job().find_id(5397444)['name']
    Out[2]: u'LD0091.part1.wasp1.sbatch'
    type(job().find_id(5397444)['name'])
    Out[3]: unicode

python3::
    
    from pyslurm import job
    job().find_id(5397444)['name']
    Out[5]: "b'LD0091.part1.wasp1.sbatch'" 
    type(job().find_id(5397444)['name'])
    Out[6]: str

Any ideas? Right now I am handling it by just stripping out the ``b''`` characters at either end of the string. That isn't very elegant (or sensible) though, so I think a fix could be worth it.

**Comment by gingergeeks** [comment]
Mike,
         This is one of the reasons why ticket #3 was created to handle the fundamental differences in unicode and byte string handling. I will be looking at this soon and if we can have one code base for both python2 and python3.

**Comment by MikeDacre** [comment]
Thanks for the info, I wonder if you can just explicitly set all of the strings to be unicode as suggested here: http://python-future.org/compatible_idioms.html?highlight=unicode#unicode-text-string-literals

I can have a look into this myself when I get back to work next week as I am using your code to write a job submission tool for my lab and I want it to work with both 2 and 3.

**Comment by gingergeeks** [comment]
I will close this for now. Giovanni and I have been tracking down issues here and there. We will get to Python3 shortly so it is in plan.
