### ISSUE TITLE
Question: can pyslurm access per-partition CPU info like sinfo?

### ISSUE THREAD

**Issue by giovtorres** [gingergeeks/pyslurm#57]
Does pyslurm have access to the number of allocated/idle/other/total CPUs per partition?  I could only find the total_cpus in pyslurm.partition().

```
$ sinfo -o '%P %C'
PARTITION CPUS(A/I/O/T)
norm* 9094/794/32/9920
```

Thanks,
Giovanni

**Comment by gingergeeks** [comment]
Giovanni, 
               I will take a look when I can this holiday.

**Comment by giovtorres** [comment]
Thanks!

**Comment by gingergeeks** [comment]
Giovanni,
              Looks like sinfo is making calls out to the node structure to determine nodes in the partition and hence information that is not available in the partition structure. I wonder if an example script/class to provide the information rather than changing the underlying slurm data structure is best ?

Mark

**Comment by gingergeeks** [comment]
Update - I wonder if adding it as a function call in the partition class would work ?

**Comment by giovtorres** [comment]
I'm not really sure where is the best place for this data.  I agree that you wouldn't want to change the underlying slurm data structure.  It doesn't have to go in the partition structure, although that would be a logical place for it since the data is per-partition.  Perhaps a function call in the partition class would do indeed.

**Comment by gingergeeks** [comment]
Giovanni,
               How many nodes, partitions do you have and do nodes appear in multiple partitions ? I'm thinking on how to achieve this without a massive hit on the query.

Mark

**Comment by giovtorres** [comment]
Currently, 2100 nodes, but going up to 4000 in year.

**Comment by gingergeeks** [comment]
Giovanni,
               Can you time the node get method for me.... similar to below but you will may need to change -

    import pyslurm as slurm
    import time
    start = time.time()
    Nodes = slurm.node()
    end = time.time()
    print("Node init method - %5.2f" % (end-start))

    start = time.time()
    node_dict = Nodes.get()
    end = time.time()
    print("Node get method - %5.2f" % (end-start))

**Comment by giovtorres** [comment]
```
$ /usr/bin/python test-node-get.py
Node init method -  0.09
Node get method -  0.06

$ /usr/bin/python test-node-get.py
Node init method -  0.08
Node get method -  0.08

$ /usr/bin/python test-node-get.py
Node init method -  0.07
Node get method -  0.65

$ /usr/bin/python test-node-get.py
Node init method -  0.09
Node get method -  0.07

$ /usr/bin/python test-node-get.py
Node init method -  0.08
Node get method -  0.06

$ /usr/bin/python test-node-get.py
Node init method -  0.08
Node get method -  0.07
```

**Comment by gingergeeks** [comment]
Thanks, that's not as bad as I thought it might be. I'm hoping that has data in it :)

**Comment by giovtorres** [comment]
I thought that was a bit fast too, but there's stuff in there:

```
$ /usr/bin/python test-node-get.py
Node init method -  0.09
Node get method -  0.07
Items in node_dict - 2125
```

**Comment by giovtorres** [comment]
I'll raise this as a feature request later on, since it appears it can't be done with a simple api call.
