### ISSUE TITLE
pyslurm.node().get() doesn't work as expected anymore. Regression?

### ISSUE THREAD

**Issue by giovtorres** [gingergeeks/pyslurm#58]
I have a script that does the following:
```python
pyslurmnode = pyslurm.node()
nodeinfo = pyslurmnode.find_id(node)
```
nodeinfo is now always returning an empty {}.  If I revert to an older version of pyslurm, nodeinfo is populated correctly.  I think the problem may be in this commit: 6110534f26aef59821960d7a4b236a91b2550e43.  self.get() was taken out of the node constructor.  It is there, however, for the job class constructor (https://github.com/gingergeeks/pyslurm/blob/slurm-14.11.5/pyslurm/pyslurm.pyx#L1678)

I can get around this by manually calling get() after initializing the pyslurm.node object:
```
pyslurmnode = pyslurm.node()
pyslurmnode.get()
nodeinfo = pyslurmnode.find_id(node)
```

Stringing together a method call after object initialization also no longer works in the interpreter console for node():
```
>>> pprint(pyslurm.node().find_id("cn0001"))
{}
```

Thoughts?

**Comment by gingergeeks** [comment]
You are correct Giovanni, I did remove the self.get call in the constructor because I noticed that somehow the code was calling it twice during first use. I will implement the call until I can think of a better way.

**Comment by giovtorres** [comment]
Does it also get called twice in pyslurm.job() then?

**Comment by gingergeeks** [comment]
Yes, I basically used the same idea for the other classes. I decide to load the class with data so save making the first get/load call.

**Comment by gingergeeks** [comment]
Giovanni, I've added the self.get() call in the node class constructor for branch 14.11 and onwards. Sorry for the confusion, I will find the cause of the double load whilst leaving the get method in the constructor. Please close when you have retested the latest commit and you are happy.

**Comment by giovtorres** [comment]
Done.  Old scripts work as before.  Thanks Mark!
