### ISSUE TITLE
ctypedef => cdef

### ISSUE THREAD

**Issue by chilly** [gingergeeks/pyslurm#64]
some of your code in slurm.pxd:
like:
"ctypedef enum connection_type:"  // wrong
the code can not be compiled in Cython 0.23 .

**Comment by giovtorres** [comment]
What version of SLURM do you have? What branch of PySLURM are you trying to build?  What error message do you get when trying to build? I am using Cython 0.23.4 with no errors.

**Comment by chilly** [comment]
pyslurm is branch  2.6.0  . slurm is  2.6.9 .    I changed setup.py support 2.6.9 to execute  "python setup.py build".

**Comment by giovtorres** [comment]
I pushed a new branch and fixed the errors you reported in 95911fe6.  Checkout the slurm-2.6.9 branch and try recompiling.

**Comment by chilly** [comment]
Great work!
