### ISSUE TITLE
API improvements and discussions?

### ISSUE THREAD

**Issue by rezib** [gingergeeks/pyslurm#68]
I saw the following change in the README:

> Currently PySlurm is under development to move from it's thin layer on top of the Slurm C API to an object orientated interface.

Are there ongoing discussions about ways to improve PySLURM API? I also saw there were new drafts in the wiki, but found nothing about the API.

What do you think about creating a mailing-list (on sourceforge or so) to discuss about this and sync the development efforts on PySLURM?

**Comment by gingergeeks** [comment]
Remi,
         Hi there ! There are not really any discussions going on atm other than between Giovanni and myself as we try to clean up the code base a little and track down memory leaks before we start work on 16.08.5. I agree it might make sense to create some sort of mailing list and we are happy to have others help us improve the existing code base.

Mark

**Comment by giovtorres** [comment]
I created a google group for this: https://groups.google.com/forum/#!forum/pyslurm

Go ahead and sign up.
